name: Test Pull Request

on:
  push:
    branches-ignore:
      - dev
      - prod
      - release/*

permissions:
  contents: read

jobs:
  merge-checks-complete:
    runs-on: ubuntu-latest
    steps:
      - name: merge-checks-complete
        run: echo 0
